# Introduction to Scikit-Learn (sklearn)

This Notebook demonstrates some of the most useful functions of the beautiful scikit learn library.

What we're going to cover:
1. An end-to-end Scikit-Learn workflow.
2. Getting the Data ready.
3. Choose the right estimator (or model)/ algorithm for our problems.
4. Fit the model/algorithm and use it to make predictions on ourr data.
5. Evaluate the model.
6. Improve the model.
7. Save and load a trained mode,
8. Putting it all together.

## An End-to-End Scikit-Learn Workflow.

In [ ]:
# 1. Get the data ready.
import pandas as pd
import numpy as np

heart_disease = pd.read_csv("./data/heart-disease.csv")

heart_disease

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [ ]:
# Create X (features matrix)
X = heart_disease.drop("target", axis=1)

# Create y (labels)
y= heart_disease["target"]

In [ ]:
# Ignoring the Warnings.
import warnings
warnings.filterwarnings("ignore")

In [ ]:
# Get the version info of sklearn.
import sklearn
sklearn.show_versions()

System:
    python: 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]
executable: e:\VS Code Programs\Python\.venv\Scripts\python.exe
   machine: Windows-10-10.0.19045-SP0

Python dependencies:
      sklearn: 1.7.2
          pip: 26.1.2
   setuptools: 80.9.0
        numpy: 2.4.6
        scipy: 1.17.1
       Cython: 3.0.2
       pandas: 2.3.3
   matplotlib: 3.11.0
       joblib: 1.5.2
threadpoolctl: 3.6.0

Built with OpenMP: True

threadpoolctl info:
       user_api: blas
   internal_api: openblas
    num_threads: 8
         prefix: libscipy_openblas
       filepath: E:\VS Code Programs\Python\.venv\Lib\site-packages\numpy.libs\libscipy_openblas64_-63c857e738469261263c764a36be9436.dll
        version: 0.3.31.188.0
threading_layer: pthreads
   architecture: Haswell

       user_api: openmp
   internal_api: openmp
    num_threads: 8
         prefix: vcomp
       filepath: E:\VS Code Programs\Python\.venv\Lib\site-packages\sklearn\.libs\vcomp140.dll
        version: None

       user_api: blas
   internal_api: openblas
    num_threads: 8
         prefix: libscipy_openblas
       filepath: E:\VS Code Programs\Python\.venv\Lib\site-packages\scipy.libs\libscipy_openblas-64eda39e79589aedb16f58e5547eb599.dll
        version: 0.3.30
threading_layer: pthreads
   architecture: Haswell

In [ ]:
# 2. Choose the right model and hyperparameters.
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()

# We'll keep the default hyperparameters.
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [ ]:
# 3. Fit the model to the data.
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [ ]:
clf.fit(X_train, y_train)

RandomForestClassifier()

In [ ]:
X_train

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
256,58,1,0,128,259,0,0,130,1,3.0,1,2,3
219,48,1,0,130,256,1,0,150,1,0.0,2,2,3
210,57,1,2,128,229,0,0,150,0,0.4,1,1,3
174,60,1,0,130,206,0,0,132,1,2.4,1,2,3
277,57,1,1,124,261,0,1,141,0,0.3,2,0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
213,61,0,0,145,307,0,0,146,1,1.0,1,0,3
82,60,0,2,102,318,0,1,160,0,0.0,2,1,2
259,38,1,3,120,231,0,1,182,1,3.8,1,0,3
180,55,1,0,132,353,0,1,132,1,1.2,1,1,3
142,42,0,2,120,209,0,1,173,0,0.0,1,0,2

In [ ]:
X_test

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
73,51,1,0,140,261,0,0,186,1,0.0,2,0,2
115,37,0,2,120,215,0,1,170,0,0.0,2,0,2
163,38,1,2,138,175,0,1,173,0,0.0,2,4,2
45,52,1,1,120,325,0,1,172,0,0.2,2,0,2
68,44,1,1,120,220,0,1,170,0,0.0,2,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,53,1,0,142,226,0,0,111,1,0.0,2,0,3
181,65,0,0,150,225,0,0,114,0,1.0,1,3,3
138,57,1,0,110,201,0,1,126,1,1.5,1,0,1
200,44,1,0,110,197,0,0,177,0,0.0,2,1,2
246,56,0,0,134,409,0,0,150,1,1.9,1,2,3

In [ ]:
y_train

256    0
219    0
210    0
174    0
277    0
      ..
213    0
82     1
259    0
180    0
142    1
Name: target, Length: 242, dtype: int64

In [ ]:
# Make a prediction

# # Gives an Error as its not the same shape as the train/test data.
# y_label = clf.predict(np.array[1, 2 ,3 ,4])

y_preds = clf.predict(X_test)

y_preds

array([1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
y_test

73     1
115    1
163    1
45     1
68     1
      ..
95     1
181    0
138    1
200    0
246    0
Name: target, Length: 61, dtype: int64

In [ ]:
# 4. Evaulate the Model on the training data and test data.
clf.score(X_train, y_train)

1.0

In [ ]:
clf.score(X_test, y_test)

0.7868852459016393

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(classification_report(y_test, y_preds))

              precision    recall  f1-score   support

           0       0.76      0.79      0.77        28
           1       0.81      0.79      0.80        33

    accuracy                           0.79        61
   macro avg       0.79      0.79      0.79        61
weighted avg       0.79      0.79      0.79        61

In [ ]:
confusion_matrix(y_test, y_preds)

array([[22,  6],
       [ 7, 26]])

In [ ]:
accuracy_score(y_test, y_preds)

0.7868852459016393

In [ ]:
# 5. Improve the Model.
# Try different amount of n_estimators

np.random.seed(42)
for i in range(10, 100, 10):
    print(f"Trying model with {i} estimators..")
    clf = RandomForestClassifier(n_estimators=i).fit(X_train, y_train)

    print(f"Model accuracy on test set: {clf.score(X_test, y_test) * 100:.2f}%")
    print("")

Trying model with 10 estimators..
Model accuracy on test set: 80.33%

Trying model with 20 estimators..
Model accuracy on test set: 80.33%

Trying model with 30 estimators..
Model accuracy on test set: 78.69%

Trying model with 40 estimators..
Model accuracy on test set: 80.33%

Trying model with 50 estimators..
Model accuracy on test set: 83.61%

Trying model with 60 estimators..
Model accuracy on test set: 80.33%

Trying model with 70 estimators..
Model accuracy on test set: 78.69%

Trying model with 80 estimators..
Model accuracy on test set: 80.33%

Trying model with 90 estimators..
Model accuracy on test set: 81.97%

In [ ]:
# 6. Save a model and load it.
import pickle

pickle.dump(clf, open("./model/random_forest_model_1.pkl", 'wb'))

In [ ]:
loaded_model = pickle.load(open("./model/random_forest_model_1.pkl", 'rb'))

loaded_model.score(X_test, y_test)

0.819672131147541

# Getting Our Data Ready: Splitting our Data

In [ ]:
# Standard Imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## 1. Getting our data ready to be used with machine learning.

Three main things we have to:

1. Split the data into features and labels (usually `X` & `y`).
2. Filling (also called imputing) or disregarding missing values.
3. Converting non-numerical values to numerical values (also called feature enconding).

In [ ]:
heart_disease = pd.read_csv("./data/heart-disease.csv")

heart_disease.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [ ]:
X = heart_disease.drop("target", axis=1)
X.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2

In [ ]:
y = heart_disease["target"]
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [ ]:
# Split the data into training and test sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [ ]:
len(heart_disease)

303

In [ ]:
X.shape, y.shape

((303, 13), (303,))

In [ ]:
X.shape[0] * 0.8

242.4

In [ ]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((242, 13), (61, 13), (242,), (61,))

# Getting Our Data Ready 2: Converting to Numbers

## 1.1 Make sure it's all Numerical

In [ ]:
car_sales = pd.read_csv("./data/car-sales-extended.csv")

car_sales.head()

     Make Colour  Odometer (KM)  Doors  Price
0   Honda  White          35431      4  15323
1     BMW   Blue         192714      5  19943
2   Honda  White          84714      4  28343
3  Toyota  White         154365      4  13434
4  Nissan   Blue         181577      3  14043

In [ ]:
# We treat Doors as a category, as it has cars with {3, 4, 5} doors.
car_sales["Doors"].value_counts()

Doors
4    856
5     79
3     65
Name: count, dtype: int64

In [ ]:
len(car_sales)

1000

In [ ]:
car_sales.dtypes

Make             object
Colour           object
Odometer (KM)     int64
Doors             int64
Price             int64
dtype: object

In [ ]:
# Split the data into 'X' and 'y'.
X = car_sales.drop("Price", axis=1)
y = car_sales["Price"]

# Split into training and test set.
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [ ]:
# Build machine learning model.

# It Gave Error: "As the data wasn't Numeric"

# from sklearn.ensemble import RandomForestRegressor

# model = RandomForestRegressor()
# model.fit(X_train, y_train)

In [ ]:
X.head()

     Make Colour  Odometer (KM)  Doors
0   Honda  White          35431      4
1     BMW   Blue         192714      5
2   Honda  White          84714      4
3  Toyota  White         154365      4
4  Nissan   Blue         181577      3

In [ ]:
# Turn the categories into numbers.
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Make", "Colour", "Doors"]
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot", one_hot, categorical_features)], remainder = "passthrough")

transformed_X = transformer.fit_transform(X)
transformed_X

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 3.54310e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        1.00000e+00, 1.92714e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 8.47140e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 6.66040e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.15883e+05],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.48360e+05]], shape=(1000, 13))

In [ ]:
pd.DataFrame(transformed_X)

      0    1    2    3    4    5    6    7    8    9    10   11        12
0    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   35431.0
1    1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  192714.0
2    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   84714.0
3    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  154365.0
4    0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  181577.0
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...       ...
995  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   35820.0
996  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  155144.0
997  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   66604.0
998  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  215883.0
999  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  248360.0

[1000 rows x 13 columns]

In [ ]:
# Another method using 'numpy'.

dummies = pd.get_dummies(car_sales[["Make", "Colour", "Doors"]])
dummies

,Doors,Make_BMW,Make_Honda,Make_Nissan,Make_Toyota,Colour_Black,Colour_Blue,Colour_Green,Colour_Red,Colour_White
0,4,False,True,False,False,False,False,False,False,True
1,5,True,False,False,False,False,True,False,False,False
2,4,False,True,False,False,False,False,False,False,True
3,4,False,False,False,True,False,False,False,False,True
4,3,False,False,True,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...
995,4,False,False,False,True,True,False,False,False,False
996,3,False,False,True,False,False,False,False,False,True
997,4,False,False,True,False,False,True,False,False,False
998,4,False,True,False,False,False,False,False,False,True
999,4,False,False,False,True,False,True,False,False,False

In [ ]:
# Let's refit the model.
np.random.seed(42)
X_train, X_test, y_train, y_test = train_test_split(transformed_X, y, test_size=0.2)

model.fit(X_train, y_train)

RandomForestRegressor()

In [ ]:
model.score(X_test, y_test)

0.3235867221569877