# Manipulating Data

In [381]:
# Importing Important Things.

import pandas as pd

car_sales = pd.read_csv("./data/car-sales.csv")

car_sales

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [382]:
car_sales["Make"].str.lower()

0    toyota
1     honda
2    toyota
3       bmw
4    nissan
5    toyota
6     honda
7     honda
8    toyota
9    nissan
Name: Make, dtype: object

In [383]:
# The change didn't Save because we didnt really altered or manipulated the Real Column
# Rather it was just a copy of it or a memory refernce.

car_sales

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [384]:
car_sales["Make"] = car_sales["Make"].str.lower()

In [385]:
car_sales

     Make Colour  Odometer (KM)  Doors       Price
0  toyota  White         150043      4   $4,000.00
1   honda    Red          87899      4   $5,000.00
2  toyota   Blue          32549      3   $7,000.00
3     bmw  Black          11179      5  $22,000.00
4  nissan  White         213095      4   $3,500.00
5  toyota  Green          99213      4   $4,500.00
6   honda   Blue          45698      4   $7,500.00
7   honda   Blue          54738      4   $7,000.00
8  toyota  White          60000      4   $6,250.00
9  nissan  White          31600      4   $9,700.00

In [386]:
car_sales_missing = pd.read_csv("./data/car-sales-missing-data.csv")

In [387]:
car_sales_missing

     Make Colour  Odometer  Doors    Price
0  Toyota  White  150043.0    4.0   $4,000
1   Honda    Red   87899.0    4.0   $5,000
2  Toyota   Blue       NaN    3.0   $7,000
3     BMW  Black   11179.0    5.0  $22,000
4  Nissan  White  213095.0    4.0   $3,500
5  Toyota  Green       NaN    4.0   $4,500
6   Honda    NaN       NaN    4.0   $7,500
7   Honda   Blue       NaN    4.0      NaN
8  Toyota  White   60000.0    NaN      NaN
9     NaN  White   31600.0    4.0   $9,700

In [388]:
car_sales_missing["Odometer"].mean()

np.float64(92302.66666666667)

In [389]:
car_sales_missing["Odometer"].fillna(car_sales_missing["Odometer"].mean())

0    150043.000000
1     87899.000000
2     92302.666667
3     11179.000000
4    213095.000000
5     92302.666667
6     92302.666667
7     92302.666667
8     60000.000000
9     31600.000000
Name: Odometer, dtype: float64

In [390]:
car_sales_missing

     Make Colour  Odometer  Doors    Price
0  Toyota  White  150043.0    4.0   $4,000
1   Honda    Red   87899.0    4.0   $5,000
2  Toyota   Blue       NaN    3.0   $7,000
3     BMW  Black   11179.0    5.0  $22,000
4  Nissan  White  213095.0    4.0   $3,500
5  Toyota  Green       NaN    4.0   $4,500
6   Honda    NaN       NaN    4.0   $7,500
7   Honda   Blue       NaN    4.0      NaN
8  Toyota  White   60000.0    NaN      NaN
9     NaN  White   31600.0    4.0   $9,700

In [391]:
# Using Inplace to re-assign Value.

car_sales_missing["Odometer"].fillna(car_sales_missing["Odometer"].mean(), inplace=True)

C:\Users\{Sachin}\AppData\Local\Temp\ipykernel_10584\1651745242.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  car_sales_missing["Odometer"].fillna(car_sales_missing["Odometer"].mean(), inplace=True)

In [392]:
car_sales_missing

     Make Colour       Odometer  Doors    Price
0  Toyota  White  150043.000000    4.0   $4,000
1   Honda    Red   87899.000000    4.0   $5,000
2  Toyota   Blue   92302.666667    3.0   $7,000
3     BMW  Black   11179.000000    5.0  $22,000
4  Nissan  White  213095.000000    4.0   $3,500
5  Toyota  Green   92302.666667    4.0   $4,500
6   Honda    NaN   92302.666667    4.0   $7,500
7   Honda   Blue   92302.666667    4.0      NaN
8  Toyota  White   60000.000000    NaN      NaN
9     NaN  White   31600.000000    4.0   $9,700

In [393]:
car_sales_missing.dropna()

     Make Colour       Odometer  Doors    Price
0  Toyota  White  150043.000000    4.0   $4,000
1   Honda    Red   87899.000000    4.0   $5,000
2  Toyota   Blue   92302.666667    3.0   $7,000
3     BMW  Black   11179.000000    5.0  $22,000
4  Nissan  White  213095.000000    4.0   $3,500
5  Toyota  Green   92302.666667    4.0   $4,500

In [394]:
car_sales_missing

     Make Colour       Odometer  Doors    Price
0  Toyota  White  150043.000000    4.0   $4,000
1   Honda    Red   87899.000000    4.0   $5,000
2  Toyota   Blue   92302.666667    3.0   $7,000
3     BMW  Black   11179.000000    5.0  $22,000
4  Nissan  White  213095.000000    4.0   $3,500
5  Toyota  Green   92302.666667    4.0   $4,500
6   Honda    NaN   92302.666667    4.0   $7,500
7   Honda   Blue   92302.666667    4.0      NaN
8  Toyota  White   60000.000000    NaN      NaN
9     NaN  White   31600.000000    4.0   $9,700

In [395]:
car_sales_missing.dropna(inplace=True)

In [396]:
car_sales_missing

     Make Colour       Odometer  Doors    Price
0  Toyota  White  150043.000000    4.0   $4,000
1   Honda    Red   87899.000000    4.0   $5,000
2  Toyota   Blue   92302.666667    3.0   $7,000
3     BMW  Black   11179.000000    5.0  $22,000
4  Nissan  White  213095.000000    4.0   $3,500
5  Toyota  Green   92302.666667    4.0   $4,500

In [397]:
car_sales_missing = pd.read_csv("./data/car-sales-missing-data.csv")

car_sales_missing

     Make Colour  Odometer  Doors    Price
0  Toyota  White  150043.0    4.0   $4,000
1   Honda    Red   87899.0    4.0   $5,000
2  Toyota   Blue       NaN    3.0   $7,000
3     BMW  Black   11179.0    5.0  $22,000
4  Nissan  White  213095.0    4.0   $3,500
5  Toyota  Green       NaN    4.0   $4,500
6   Honda    NaN       NaN    4.0   $7,500
7   Honda   Blue       NaN    4.0      NaN
8  Toyota  White   60000.0    NaN      NaN
9     NaN  White   31600.0    4.0   $9,700

In [398]:
car_sales_missing_dropped = car_sales_missing.dropna()

car_sales_missing_dropped

     Make Colour  Odometer  Doors    Price
0  Toyota  White  150043.0    4.0   $4,000
1   Honda    Red   87899.0    4.0   $5,000
3     BMW  Black   11179.0    5.0  $22,000
4  Nissan  White  213095.0    4.0   $3,500

In [399]:
car_sales_missing_dropped.to_csv("./data/car-sales-missing-dropped.csv")

# Manipulating Data 2

In [400]:
# Column from series

seats_column = pd.Series([5, 5, 5, 5, 5])

# New Column called seats

car_sales["Seats"] = seats_column

car_sales

     Make Colour  Odometer (KM)  Doors       Price  Seats
0  toyota  White         150043      4   $4,000.00    5.0
1   honda    Red          87899      4   $5,000.00    5.0
2  toyota   Blue          32549      3   $7,000.00    5.0
3     bmw  Black          11179      5  $22,000.00    5.0
4  nissan  White         213095      4   $3,500.00    5.0
5  toyota  Green          99213      4   $4,500.00    NaN
6   honda   Blue          45698      4   $7,500.00    NaN
7   honda   Blue          54738      4   $7,000.00    NaN
8  toyota  White          60000      4   $6,250.00    NaN
9  nissan  White          31600      4   $9,700.00    NaN

In [401]:
car_sales["Seats"].fillna(5, inplace=True)

C:\Users\{Sachin}\AppData\Local\Temp\ipykernel_10584\1647811259.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  car_sales["Seats"].fillna(5, inplace=True)

In [402]:
car_sales

     Make Colour  Odometer (KM)  Doors       Price  Seats
0  toyota  White         150043      4   $4,000.00    5.0
1   honda    Red          87899      4   $5,000.00    5.0
2  toyota   Blue          32549      3   $7,000.00    5.0
3     bmw  Black          11179      5  $22,000.00    5.0
4  nissan  White         213095      4   $3,500.00    5.0
5  toyota  Green          99213      4   $4,500.00    5.0
6   honda   Blue          45698      4   $7,500.00    5.0
7   honda   Blue          54738      4   $7,000.00    5.0
8  toyota  White          60000      4   $6,250.00    5.0
9  nissan  White          31600      4   $9,700.00    5.0

In [403]:
# Column from Python List.

fuel_economy = [7.5, 9.2, 5.0, 9.6, 8.7]
# car_sales["Fuel per 100KM"] = fuel_economy

# # It Gave Error: ValueError: Length of values (5) does not match length of index (10)

# Fix: We need need data, so that no field is empty as it will throw error.

In [404]:
fuel_economy = [7.5, 9.2, 5.0, 9.6, 8.7, 4.7, 7.6, 8.7, 3.0, 4.5]
car_sales["Fuel per 100KM"] = fuel_economy

car_sales

     Make Colour  Odometer (KM)  Doors       Price  Seats  Fuel per 100KM
0  toyota  White         150043      4   $4,000.00    5.0             7.5
1   honda    Red          87899      4   $5,000.00    5.0             9.2
2  toyota   Blue          32549      3   $7,000.00    5.0             5.0
3     bmw  Black          11179      5  $22,000.00    5.0             9.6
4  nissan  White         213095      4   $3,500.00    5.0             8.7
5  toyota  Green          99213      4   $4,500.00    5.0             4.7
6   honda   Blue          45698      4   $7,500.00    5.0             7.6
7   honda   Blue          54738      4   $7,000.00    5.0             8.7
8  toyota  White          60000      4   $6,250.00    5.0             3.0
9  nissan  White          31600      4   $9,700.00    5.0             4.5

### Create a Column from Another Column

In [405]:
car_sales["Total fuel used"] = car_sales["Odometer (KM)"] / 100 * car_sales["Fuel per 100KM"]

In [406]:
car_sales

,Make,Colour,Odometer (KM),Doors,Price,Seats,Fuel per 100KM,Total fuel used
0,toyota,White,150043,4,"$4,000.00",5.0,7.5,11253.225
1,honda,Red,87899,4,"$5,000.00",5.0,9.2,8086.708
2,toyota,Blue,32549,3,"$7,000.00",5.0,5.0,1627.450
3,bmw,Black,11179,5,"$22,000.00",5.0,9.6,1073.184
4,nissan,White,213095,4,"$3,500.00",5.0,8.7,18539.265
5,toyota,Green,99213,4,"$4,500.00",5.0,4.7,4663.011
6,honda,Blue,45698,4,"$7,500.00",5.0,7.6,3473.048
7,honda,Blue,54738,4,"$7,000.00",5.0,8.7,4762.206
8,toyota,White,60000,4,"$6,250.00",5.0,3.0,1800.000
9,nissan,White,31600,4,"$9,700.00",5.0,4.5,1422.000

In [407]:
# Renaming it but, it causes it to create a new Column.
car_sales["Total fuel used (L)"] = car_sales["Odometer (KM)"] / 100 * car_sales["Fuel per 100KM"]

car_sales

,Make,Colour,Odometer (KM),Doors,Price,Seats,Fuel per 100KM,Total fuel used,Total fuel used (L)
0,toyota,White,150043,4,"$4,000.00",5.0,7.5,11253.225,11253.225
1,honda,Red,87899,4,"$5,000.00",5.0,9.2,8086.708,8086.708
2,toyota,Blue,32549,3,"$7,000.00",5.0,5.0,1627.450,1627.450
3,bmw,Black,11179,5,"$22,000.00",5.0,9.6,1073.184,1073.184
4,nissan,White,213095,4,"$3,500.00",5.0,8.7,18539.265,18539.265
5,toyota,Green,99213,4,"$4,500.00",5.0,4.7,4663.011,4663.011
6,honda,Blue,45698,4,"$7,500.00",5.0,7.6,3473.048,3473.048
7,honda,Blue,54738,4,"$7,000.00",5.0,8.7,4762.206,4762.206
8,toyota,White,60000,4,"$6,250.00",5.0,3.0,1800.000,1800.000
9,nissan,White,31600,4,"$9,700.00",5.0,4.5,1422.000,1422.000

### Create a Column from a single Value.

In [408]:
car_sales["Number of Wheels"] = 4
car_sales

,Make,Colour,Odometer (KM),Doors,Price,Seats,Fuel per 100KM,Total fuel used,Total fuel used (L),Number of Wheels
0,toyota,White,150043,4,"$4,000.00",5.0,7.5,11253.225,11253.225,4
1,honda,Red,87899,4,"$5,000.00",5.0,9.2,8086.708,8086.708,4
2,toyota,Blue,32549,3,"$7,000.00",5.0,5.0,1627.450,1627.450,4
3,bmw,Black,11179,5,"$22,000.00",5.0,9.6,1073.184,1073.184,4
4,nissan,White,213095,4,"$3,500.00",5.0,8.7,18539.265,18539.265,4
5,toyota,Green,99213,4,"$4,500.00",5.0,4.7,4663.011,4663.011,4
6,honda,Blue,45698,4,"$7,500.00",5.0,7.6,3473.048,3473.048,4
7,honda,Blue,54738,4,"$7,000.00",5.0,8.7,4762.206,4762.206,4
8,toyota,White,60000,4,"$6,250.00",5.0,3.0,1800.000,1800.000,4
9,nissan,White,31600,4,"$9,700.00",5.0,4.5,1422.000,1422.000,4

In [409]:
car_sales["Passed Road Saftey"] = True

car_sales.dtypes

Make                    object
Colour                  object
Odometer (KM)            int64
Doors                    int64
Price                   object
Seats                  float64
Fuel per 100KM         float64
Total fuel used        float64
Total fuel used (L)    float64
Number of Wheels         int64
Passed Road Saftey        bool
dtype: object

In [410]:
car_sales

,Make,Colour,Odometer (KM),Doors,Price,Seats,Fuel per 100KM,Total fuel used,Total fuel used (L),Number of Wheels,Passed Road Saftey
0,toyota,White,150043,4,"$4,000.00",5.0,7.5,11253.225,11253.225,4,True
1,honda,Red,87899,4,"$5,000.00",5.0,9.2,8086.708,8086.708,4,True
2,toyota,Blue,32549,3,"$7,000.00",5.0,5.0,1627.450,1627.450,4,True
3,bmw,Black,11179,5,"$22,000.00",5.0,9.6,1073.184,1073.184,4,True
4,nissan,White,213095,4,"$3,500.00",5.0,8.7,18539.265,18539.265,4,True
5,toyota,Green,99213,4,"$4,500.00",5.0,4.7,4663.011,4663.011,4,True
6,honda,Blue,45698,4,"$7,500.00",5.0,7.6,3473.048,3473.048,4,True
7,honda,Blue,54738,4,"$7,000.00",5.0,8.7,4762.206,4762.206,4,True
8,toyota,White,60000,4,"$6,250.00",5.0,3.0,1800.000,1800.000,4,True
9,nissan,White,31600,4,"$9,700.00",5.0,4.5,1422.000,1422.000,4,True

### Removing or Dropping a Column.

In [411]:
car_sales.drop("Total fuel used", axis = 1)

# We need to assign it.

car_sales = car_sales.drop("Total fuel used", axis = 1)

In [412]:
car_sales

,Make,Colour,Odometer (KM),Doors,Price,Seats,Fuel per 100KM,Total fuel used (L),Number of Wheels,Passed Road Saftey
0,toyota,White,150043,4,"$4,000.00",5.0,7.5,11253.225,4,True
1,honda,Red,87899,4,"$5,000.00",5.0,9.2,8086.708,4,True
2,toyota,Blue,32549,3,"$7,000.00",5.0,5.0,1627.450,4,True
3,bmw,Black,11179,5,"$22,000.00",5.0,9.6,1073.184,4,True
4,nissan,White,213095,4,"$3,500.00",5.0,8.7,18539.265,4,True
5,toyota,Green,99213,4,"$4,500.00",5.0,4.7,4663.011,4,True
6,honda,Blue,45698,4,"$7,500.00",5.0,7.6,3473.048,4,True
7,honda,Blue,54738,4,"$7,000.00",5.0,8.7,4762.206,4,True
8,toyota,White,60000,4,"$6,250.00",5.0,3.0,1800.000,4,True
9,nissan,White,31600,4,"$9,700.00",5.0,4.5,1422.000,4,True