In [48]:
import pandas as pd

# 2 Main Datatypes:
## 1. Series.
## 2. Dataframe.

### 1. Series Datatype.

In [49]:
series = pd.Series(["BMW", "Toyota", "Honda"])

series

0       BMW
1    Toyota
2     Honda
dtype: object

### series = 1-Dimensional

In [50]:
colours = pd.Series(['Red', 'Blue', 'White'])

colours

0      Red
1     Blue
2    White
dtype: object

### 2. DataFrames Datatype.

### Dataframe =  2-Dimensional

In [51]:
car_data = pd.DataFrame({"Car Make": series, "Colour": colours})

car_data

  Car Make Colour
0      BMW    Red
1   Toyota   Blue
2    Honda  White

### Import Data into a dataframe.

In [52]:
car_sales = pd.read_csv("car-sales.csv")

car_sales

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

### Exporting a Dataframe

In [53]:
car_sales.to_csv("Exported-car-sales.csv")

In [54]:
# To export to an Excel file.

# car_sales.to_excel("Exported-car-sales.xlsx", index = False)

In [55]:
exported_car_sales = pd.read_csv("exported-car-sales.csv")

exported_car_sales

   Unnamed: 0    Make Colour  Odometer (KM)  Doors       Price
0           0  Toyota  White         150043      4   $4,000.00
1           1   Honda    Red          87899      4   $5,000.00
2           2  Toyota   Blue          32549      3   $7,000.00
3           3     BMW  Black          11179      5  $22,000.00
4           4  Nissan  White         213095      4   $3,500.00
5           5  Toyota  Green          99213      4   $4,500.00
6           6   Honda   Blue          45698      4   $7,500.00
7           7   Honda   Blue          54738      4   $7,000.00
8           8  Toyota  White          60000      4   $6,250.00
9           9  Nissan  White          31600      4   $9,700.00

In [56]:
## Fixing the Index also being Included in the export

In [57]:
car_sales.to_csv("Exported-car-sales.csv", index = False)

In [58]:
exported_car_sales = pd.read_csv("exported-car-sales.csv")

exported_car_sales

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

# Describing Data with Pandas

In [59]:
# Attribute
car_sales.dtypes

# Function
# car_sales.to_csv()

Make             object
Colour           object
Odometer (KM)     int64
Doors             int64
Price            object
dtype: object

## Attributes

In [60]:
car_sales.columns

Index(['Make', 'Colour', 'Odometer (KM)', 'Doors', 'Price'], dtype='object')

In [61]:
car_columns = car_sales.columns
car_columns

Index(['Make', 'Colour', 'Odometer (KM)', 'Doors', 'Price'], dtype='object')

In [62]:
# car_columns.index     -> This is wrong as it doesn't has any index.

car_sales.index

RangeIndex(start=0, stop=10, step=1)

In [63]:
car_sales

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

## Functions

In [64]:
# Describe only works on numeric columns.
car_sales.describe()

       Odometer (KM)      Doors
count      10.000000  10.000000
mean    78601.400000   4.000000
std     61983.471735   0.471405
min     11179.000000   3.000000
25%     35836.250000   4.000000
50%     57369.000000   4.000000
75%     96384.500000   4.000000
max    213095.000000   5.000000

In [65]:
car_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Make           10 non-null     object
 1   Colour         10 non-null     object
 2   Odometer (KM)  10 non-null     int64
 3   Doors          10 non-null     int64
 4   Price          10 non-null     object
dtypes: int64(2), object(3)
memory usage: 532.0+ bytes

In [66]:
car_sales.mean(numeric_only=True)

Odometer (KM)    78601.4
Doors                4.0
dtype: float64

In [67]:
car_prices = pd.Series([3000, 1500, 111250])
car_prices.mean()

np.float64(38583.333333333336)

In [68]:
car_sales.sum()

Make             ToyotaHondaToyotaBMWNissanToyotaHondaHondaToyo...
Colour               WhiteRedBlueBlackWhiteGreenBlueBlueWhiteWhite
Odometer (KM)                                               786014
Doors                                                           40
Price            $4,000.00$5,000.00$7,000.00$22,000.00$3,500.00...
dtype: object

In [69]:
car_sales["Doors"].sum()

np.int64(40)

In [70]:
len(car_sales)

10

In [71]:
car_sales

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

# Viewing and Selecting Data.

In [72]:
car_sales.head()    #Default '5'.

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00

In [73]:
car_sales.head(10)

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [74]:
car_sales.tail()

     Make Colour  Odometer (KM)  Doors      Price
5  Toyota  Green          99213      4  $4,500.00
6   Honda   Blue          45698      4  $7,500.00
7   Honda   Blue          54738      4  $7,000.00
8  Toyota  White          60000      4  $6,250.00
9  Nissan  White          31600      4  $9,700.00

In [75]:
car_sales.tail(7)

     Make Colour  Odometer (KM)  Doors       Price
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

### .loc and .iloc

In [76]:
# .loc

animals = pd.Series(['cat', 'dog', 'bird', 'panda', 'snake'])

animals

0      cat
1      dog
2     bird
3    panda
4    snake
dtype: object

In [77]:
animals = pd.Series(['cat', 'dog', 'bird', 'panda', 'snake'], index = [0, 3, 9, 8, 3])

animals

0      cat
3      dog
9     bird
8    panda
3    snake
dtype: object

In [78]:
# .loc refers to index.
animals.loc[3]

3      dog
3    snake
dtype: object

In [79]:
animals.loc[9]

'bird'

In [80]:
car_sales

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [81]:
car_sales.loc[3]

Make                    BMW
Colour                Black
Odometer (KM)         11179
Doors                     5
Price            $22,000.00
Name: 3, dtype: object

In [82]:
# .iloc

In [83]:
animals

0      cat
3      dog
9     bird
8    panda
3    snake
dtype: object

In [84]:
# .iloc refers to position.
animals.iloc[3]

'panda'

In [85]:
car_sales

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [86]:
car_sales.iloc[3]

Make                    BMW
Colour                Black
Odometer (KM)         11179
Doors                     5
Price            $22,000.00
Name: 3, dtype: object

### Slicing with .loc and .iloc

In [88]:
animals

0      cat
3      dog
9     bird
8    panda
3    snake
dtype: object

In [87]:
animals.iloc[:3]

0     cat
3     dog
9    bird
dtype: object

In [89]:
car_sales.loc[:3]

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00

In [91]:
car_sales.head(4)

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00

## Selecting a Column in a dataFrame.

In [92]:
car_sales["Make"]

0    Toyota
1     Honda
2    Toyota
3       BMW
4    Nissan
5    Toyota
6     Honda
7     Honda
8    Toyota
9    Nissan
Name: Make, dtype: object

In [96]:
car_sales["Colour"]

0    White
1      Red
2     Blue
3    Black
4    White
5    Green
6     Blue
7     Blue
8    White
9    White
Name: Colour, dtype: object

In [ ]:
# 2 Ways of Selecting a Column.
car_sales["Make"]

0    Toyota
1     Honda
2    Toyota
3       BMW
4    Nissan
5    Toyota
6     Honda
7     Honda
8    Toyota
9    Nissan
Name: Make, dtype: object

In [ ]:
car_sales.Make

# but wont work if the name has a space in it.
# car_sales.Odometer (KM)

0    Toyota
1     Honda
2    Toyota
3       BMW
4    Nissan
5    Toyota
6     Honda
7     Honda
8    Toyota
9    Nissan
Name: Make, dtype: object

In [103]:
# so we have to do this.

car_sales["Odometer (KM)"]

0    150043
1     87899
2     32549
3     11179
4    213095
5     99213
6     45698
7     54738
8     60000
9     31600
Name: Odometer (KM), dtype: int64

### Filtering the Data according to certain Conditions.

In [106]:
# Boolean Indexing.

car_sales[car_sales["Make"] == "Toyota"]

     Make Colour  Odometer (KM)  Doors      Price
0  Toyota  White         150043      4  $4,000.00
2  Toyota   Blue          32549      3  $7,000.00
5  Toyota  Green          99213      4  $4,500.00
8  Toyota  White          60000      4  $6,250.00

In [107]:
car_sales[car_sales["Odometer (KM)"] > 100000]

     Make Colour  Odometer (KM)  Doors      Price
0  Toyota  White         150043      4  $4,000.00
4  Nissan  White         213095      4  $3,500.00