# Reshaping and Transposing

In [102]:
import numpy as np

In [103]:
# Recreating the matrices.

a1 = np.array([1, 2, 3])

a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [104]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [105]:
a2.shape

(2, 3)

In [106]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [107]:
a3.shape

(2, 3, 3)

In [108]:
# a2 * a3

# Error: ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

# It gives error because the arrays are of different order in matrix mul rules.

# Fix: "reshape" the arrays.

In [109]:
a2.reshape(2, 3, 1)

array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5. ],
        [6.5]]])

In [110]:
a3.shape

(2, 3, 3)

In [111]:
a2_reshape = a2.reshape(2, 3, 1)

a2_reshape

array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5. ],
        [6.5]]])

In [112]:
a2_reshape * a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 23.1,  26.4,  29.7]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [104. , 110.5, 117. ]]])

In [113]:
# Transponse = switches the axis. (Reverse the axis)
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [114]:
a2.shape

(2, 3)

In [115]:
a2.T

array([[1. , 4. ],
       [2. , 5. ],
       [3.3, 6.5]])

In [116]:
a2.T.shape

(3, 2)

In [117]:
a3.shape

(2, 3, 3)

In [118]:
a3.T

array([[[ 1, 10],
        [ 4, 13],
        [ 7, 16]],

       [[ 2, 11],
        [ 5, 14],
        [ 8, 17]],

       [[ 3, 12],
        [ 6, 15],
        [ 9, 18]]])

In [119]:
a3.T.shape

(3, 3, 2)

# Dot Product vs Element Wise

In [120]:
np.random.seed(0)

In [121]:
mat1 = np.random.randint(10, size=(5,3))
mat2 = np.random.randint(10, size=(5,3))

In [122]:
mat1.shape, mat2.shape

((5, 3), (5, 3))

In [123]:
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]], dtype=int32)

In [124]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]], dtype=int32)

In [125]:
# Element-wise multiplication (Hadamard product)

mat1 * mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]], dtype=int32)

In [126]:
# Dot product 'np.dot' or '@'

# np.dot(mat1, mat2)
# Error: ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

# mat1 @ mat2
# ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 5 is different from 3)

In [127]:
# Transpose mat 1
mat1.T

array([[5, 3, 3, 4, 8],
       [0, 7, 5, 7, 8],
       [3, 9, 2, 6, 1]], dtype=int32)

In [128]:
mat1.T.shape, mat2.shape

((3, 5), (5, 3))

In [129]:
mat1.shape, mat2.T.shape

((5, 3), (3, 5))

In [130]:
mat3 = np.dot(mat1, mat2.T)

mat3

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]], dtype=int32)

# Dot product example (nut butter sales)

In [131]:
import pandas as pd

In [132]:
np.random.seed(0)

# Numbers of jars sold
sales_amount = np.random.randint(20, size=(5,3))
sales_amount

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]], dtype=int32)

In [133]:
# Create weekly_sales DataFrame

weekly_sales = pd.DataFrame(sales_amount, 
                            index=["Mon","Tues", "Wed", "Thurs", "Fri"],
                            columns=["Almond Butter", "Peanut Butter", "Cashew Butter"])

weekly_sales

       Almond Butter  Peanut Butter  Cashew Butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [134]:
# Create prices array.

prices = np.array([10, 8, 12])

prices

array([10,  8, 12])

In [135]:
prices.shape

(3,)

In [136]:
# # Testing to see what it makes

# # Create butter_prices DataFrame
# butter_prices = pd.DataFrame(prices)

# butter_prices

# # So the thing is its creating a DF of "rows = 3 and col = 1", even though the value passed was "row = 1 and col = 3"

In [137]:
# Create butter_prices DataFrame
butter_prices = pd.DataFrame(prices.reshape(1, 3),
                             index=["Price"],
                             columns=["Almond Butter", "Peanut Butter", "Cashew Butter"])                            

butter_prices

       Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [138]:
prices.shape

(3,)

In [139]:
sales_amount.shape

(5, 3)

In [140]:
sales_amount.T.shape

(3, 5)

In [141]:
# The shapes arent aligned so it gives error.

# total_sales = prices.dot(sales_amount)

# Error: ValueError: shapes (3,) and (5,3) not aligned: 3 (dim 0) != 5 (dim 0)

In [142]:
# Shapes aren't aligned, we need to transpose.

total_sales = prices.dot(sales_amount.T)

total_sales

array([240, 138, 458, 232, 142])

### Create daily_sales

In [143]:
butter_prices

       Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [144]:
weekly_sales

       Almond Butter  Peanut Butter  Cashew Butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [145]:
butter_prices.shape, weekly_sales.shape

((1, 3), (5, 3))

In [146]:
weekly_sales.T.shape

(3, 5)

In [147]:
daily_sales = butter_prices.dot(weekly_sales.T)

daily_sales

       Mon  Tues  Wed  Thurs  Fri
Price  240   138  458    232  142

In [148]:
type(daily_sales)

pandas.core.frame.DataFrame

In [149]:
weekly_sales

       Almond Butter  Peanut Butter  Cashew Butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [ ]:
# # It gives out an error because it not the right shape.

# weekly_sales["Total ($)"] = daily_sales

# weekly_sales

In [152]:
daily_sales.shape

(1, 5)

In [153]:
daily_sales.T.shape

(5, 1)

In [155]:
weekly_sales["Total ($)"] = daily_sales.T

weekly_sales

       Almond Butter  Peanut Butter  Cashew Butter  Total ($)
Mon               12             15              0        240
Tues               3              3              7        138
Wed                9             19             18        458
Thurs              4              6             12        232
Fri                1              6              7        142